version: "3.7"
services:
  food-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: food-db
    ports:
      - "3308:3306"
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    working_dir: /backend
    command: sh -c "npm install && npm run build && npm run start:dev"
    volumes:
      - ./backend:/backend:cached
    depends_on:
      - food-db