FROM node:carbon-alpine
#WORKDIR /backend/
# COPY package.json package-lock.json tsconfig.json tsconfig.build.json ./
# COPY src/ src/
#RUN npm install
#RUN npm run build
#CMD ["npm", "run", "start:dev"]